# Generated by Django 3.0.3 on 2020-04-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_address',
            new_name='contact_email',
        ),
    ]
