# Generated by Django 3.0.3 on 2020-05-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200421_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='no_image.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
