# Generated by Django 3.0.7 on 2020-11-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OauthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=128)),
                ('access_token_expires', models.DateTimeField(null=True)),
                ('refresh_token', models.CharField(max_length=128)),
                ('refresh_token_expires', models.DateTimeField(null=True)),
                ('gen_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
