# Generated by Django 3.0.3 on 2020-04-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200411_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'In Progress'), ('3', 'Complete')], default='1', max_length=12),
        ),
    ]
