# Generated by Django 3.0.3 on 2020-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200413_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ispushed',
            field=models.BooleanField(default=True),
        ),
    ]
