# Generated by Django 3.0.3 on 2020-04-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_ispushed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ispushed',
            field=models.BooleanField(default=False),
        ),
    ]
