# Generated by Django 3.0.3 on 2020-04-28 17:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200425_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
