# Generated by Django 3.0.2 on 2020-02-01 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='access_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 22, 18, 50, 329003)),
        ),
        migrations.AddField(
            model_name='oauthtoken',
            name='gen_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 22, 18, 50, 329101)),
        ),
    ]
