# Generated by Django 3.0.2 on 2020-02-04 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0004_auto_20200203_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='refresh_token_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 4, 14, 10, 5, 492216)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 14, 10, 5, 492115)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='gen_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 14, 10, 5, 492260)),
        ),
    ]
