# Generated by Django 3.0.3 on 2020-02-04 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0005_auto_20200204_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 21, 25, 24, 279355)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='gen_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 21, 25, 24, 279429)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='refresh_token_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 4, 21, 25, 24, 279409)),
        ),
    ]
