# Generated by Django 3.0.3 on 2020-04-11 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0009_auto_20200411_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 17, 14, 0, 172699)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='gen_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 17, 14, 0, 172783)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='refresh_token_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 11, 17, 14, 0, 172760)),
        ),
    ]
