# Generated by Django 3.0.3 on 2020-04-13 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0010_auto_20200411_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 11, 23, 11, 351988)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='gen_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 11, 23, 11, 352125)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='refresh_token_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 11, 23, 11, 352092)),
        ),
    ]
