# Generated by Django 3.0.3 on 2020-04-15 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0011_auto_20200413_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 17, 17, 34, 886553)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='gen_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 17, 17, 34, 886620)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='refresh_token_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 15, 17, 17, 34, 886600)),
        ),
    ]
