# Generated by Django 3.0.3 on 2020-05-30 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0012_auto_20200415_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_token_expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='gen_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='refresh_token_expires',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
