# Generated by Django 3.0.3 on 2020-05-30 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0013_auto_20200530_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 16, 42, 1, 830752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='gen_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 16, 42, 1, 830835, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='refresh_token_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 30, 16, 42, 1, 830809, tzinfo=utc)),
        ),
    ]
