# Generated by Django 3.0.7 on 2020-11-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0015_auto_20200530_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OauthToken',
        ),
    ]
